import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="fixed inset-0 overflow-hidden pointer-events-none flex items-center justify-center">
          <img
          src="/Pokeball.png"
          alt=""
          className="w-[300px] sm:w-[500px] md:w-[700px] opacity-20 dark:opacity-[0.04] rotate-12"
          />
        </div>

        {children}
        </body>
    </html>
  );
}
